# Generated by Django 4.0.3 on 2022-04-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_socialperson_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialperson',
            name='background',
            field=models.ImageField(upload_to='backs'),
        ),
    ]
