# Generated by Django 4.0.3 on 2022-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_socialperson_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialperson',
            name='jobs',
            field=models.CharField(default='Python Developer, Photographer', max_length=150),
            preserve_default=False,
        ),
    ]
