# Generated by Django 4.0.3 on 2022-05-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_pageimage_imagefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='category',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
