# Generated by Django 4.0.3 on 2022-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_pageimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialperson',
            name='friends',
            field=models.CharField(default='', max_length=200),
        ),
    ]
