# Generated by Django 4.0.3 on 2022-06-03 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0013_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.socialperson'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pageOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
