# Generated by Django 4.0.3 on 2022-06-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_comments_commentowner_alter_comments_pageowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='text',
        ),
    ]
